name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.5.0
      with:
        ndk-version: r26d

    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Run make
      run: make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        path: |
          libs
          obj/local/*/*.a
        if-no-files-found: error
